default:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: conveyor-dbt-devenv.cpktidvmhbdw.eu-west-1.rds.amazonaws.com
      port: 5432
      user: "conveyor"
      pass: "{{ env_var('DBT_PASSWORD') }}"
      dbname: datafy
      schema: dbt

    local:
      type: postgres
      threads: 1
      host: localhost
      port: 5433
      user: "conveyor"
      pass: "conveyor"
      dbname: conveyor
      schema: dbt

  target: dev