version: '2'
services:
  postgresql:
    image: public.ecr.aws/u9e1g0m1/postgres:13-alpine
    environment:
      - POSTGRES_DB=conveyor
      - POSTGRES_USER=conveyor
      - POSTGRES_PASSWORD=conveyor
    ports:
      - "5433:5432"